# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for B12 website generator MCP server
FROM node:lts-alpine AS builder

# set working directory
WORKDIR /app

# install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci && npm run build

# production image
FROM node:lts-alpine
WORKDIR /app

# copy built artifacts and dependencies
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/dist ./dist

# install only production dependencies
RUN npm ci --production

# expose stdio by default
ENTRYPOINT ["node", "dist/server.js"]
